name: Keep Render Alive

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Server
        run: |
          curl -s https://event-management-system-m4rt.onrender.com || true
